services:
  sftpgo:
    container_name: sftpgo
    image: drakkan/sftpgo:latest
    restart: unless-stopped
    ports:
      - "2022:2022"   # SFTP
      - "8080:8080"   # Panel de administración web (/web/admin)
      - "10080:10080" # Portal WebClient para usuarios (/web/client)
    volumes:
      - ./data:/srv/sftpgo
      - ./config:/var/lib/sftpgo

# añadir estas líneas al final del archivo para proxy inverso 
networks:
  default:
    external: true
    name: proxy
